### ISSUE TITLE
您好！2.2版本 cuda必须是8.0么？

### ISSUE THREAD

**Issue by eillenlun** [TLMichael/Perceptron#1]
我现在安装vc++2017 还是打不开程序。我是不是还要装QT之类的对应的环境呢？

**Comment by D4rkCrypto** [comment]
需要安装qt，最好是最新版本，另外需要的opencv等环境也需要满足，才可以配置好开发环境。

**Comment by TLMichael** [comment]
如果使用的是windows-cpu版本，则不需要安装QT和显卡驱动，直接双击HardhatSystem.exe运行即可；若报错，则双击运行vc_redist.x64.exe后重启电脑，之后双击HardhatSystem.exe运行即可。
如果使用的是windows-gpu版本，则需要安装显卡驱动，这需要你的电脑拥有Nvidia GPU且计算力大于3.0。

**Comment by TLMichael** [comment]
如果要自行编译这整个工程，需要自行配置很多东西，包括opencv的编译、darknet的编译、cuda的安装、QT5的安装等。
